spring:
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
  mvc:
    view:
      prefix: templates
      suffix: .html

    static-path-pattern: /static/**

logging:
  level:
    root: info

